/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertMessage: typeof import('./src/components/AlertMessage.vue')['default']
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    Footer: typeof import('./src/views/Footer.vue')['default']
    I18n: typeof import('./src/components/I18n.vue')['default']
    LeftSidebar: typeof import('./src/components/Sidebar.vue/LeftSidebar.vue')['default']
    LoadingOverlay: typeof import('./src/components/LoadingOverlay.vue')['default']
    NewGameButton: typeof import('./src/components/NewGameButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackbarMessage: typeof import('./src/components/SnackbarMessage.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
  }
}
