/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertMessage: typeof import('./src/components/AlertMessage.vue')['default']
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AssetsManagerDialog: typeof import('./src/components/Dialog/AssetsManagerDialog.vue')['default']
    AudioSource: typeof import('./src/components/AudioSource.vue')['default']
    BottomBar: typeof import('./src/components/Game/BottomBar.vue')['default']
    ClaimInviteDialog: typeof import('./src/components/Dialog/ClaimInviteDialog.vue')['default']
    ComingSoonOverlay: typeof import('./src/components/ComingSoonOverlay.vue')['default']
    ConfirmDialog: typeof import('./src/components/Dialog/ConfirmDialog.vue')['default']
    ConnectWalletBtn: typeof import('./src/components/Button/ConnectWalletBtn.vue')['default']
    DialogCloseBtn: typeof import('./src/components/DialogCloseBtn.vue')['default']
    Footer: typeof import('./src/views/Footer.vue')['default']
    FusionDialog: typeof import('./src/components/Dialog/FusionDialog.vue')['default']
    I18n: typeof import('./src/components/I18n.vue')['default']
    InputUploadFiles: typeof import('./src/components/InputUploadFiles.vue')['default']
    InviteButtons: typeof import('./src/views/Missions/InviteButtons.vue')['default']
    InviteDialog: typeof import('./src/components/Dialog/InviteDialog.vue')['default']
    ItemBlock: typeof import('./src/components/ItemBlock.vue')['default']
    ItemDialog: typeof import('./src/components/Dialog/ItemDialog.vue')['default']
    ItemForm: typeof import('./src/components/Form/ItemForm.vue')['default']
    LeftSidebar: typeof import('./src/components/Sidebar/LeftSidebar.vue')['default']
    LoadingGame: typeof import('./src/components/LoadingGame.vue')['default']
    LoadingOverlay: typeof import('./src/components/LoadingOverlay.vue')['default']
    NewGameButton: typeof import('./src/components/NewGameButton.vue')['default']
    ReferredList: typeof import('./src/views/Missions/ReferredList.vue')['default']
    ReferredUsers: typeof import('./src/views/Missions/ReferredUsers.vue')['default']
    ResultItemDialog: typeof import('./src/components/Dialog/ResultItemDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingDialog: typeof import('./src/components/Dialog/SettingDialog.vue')['default']
    SkillDialog: typeof import('./src/components/Dialog/SkillDialog.vue')['default']
    SkillForm: typeof import('./src/components/Form/SkillForm.vue')['default']
    SlotMachine: typeof import('./src/components/Game/SlotMachine.vue')['default']
    SnackbarMessage: typeof import('./src/components/SnackbarMessage.vue')['default']
    TaskBlock: typeof import('./src/components/TaskBlock.vue')['default']
    TaskDialog: typeof import('./src/components/Dialog/TaskDialog.vue')['default']
    TaskForm: typeof import('./src/components/Form/TaskForm.vue')['default']
    TaskGroupDialog: typeof import('./src/components/Dialog/TaskGroupDialog.vue')['default']
    TaskGroupForm: typeof import('./src/components/Form/TaskGroupForm.vue')['default']
    TopBar: typeof import('./src/components/Game/TopBar.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
  }
}
