/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '404': RouteRecordInfo<'404', '/404', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'dashboard-fusion': RouteRecordInfo<'dashboard-fusion', '/dashboard/fusion', Record<never, never>, Record<never, never>>,
    'dashboard-items': RouteRecordInfo<'dashboard-items', '/dashboard/items', Record<never, never>, Record<never, never>>,
    'dashboard-jackpot': RouteRecordInfo<'dashboard-jackpot', '/dashboard/jackpot', Record<never, never>, Record<never, never>>,
    'dashboard-skills': RouteRecordInfo<'dashboard-skills', '/dashboard/skills', Record<never, never>, Record<never, never>>,
    'dashboard-slot-machine': RouteRecordInfo<'dashboard-slot-machine', '/dashboard/slot-machine', Record<never, never>, Record<never, never>>,
    'dashboard-task-group': RouteRecordInfo<'dashboard-task-group', '/dashboard/task-group', Record<never, never>, Record<never, never>>,
    'dashboard-tasks': RouteRecordInfo<'dashboard-tasks', '/dashboard/tasks', Record<never, never>, Record<never, never>>,
    'dashboard-users': RouteRecordInfo<'dashboard-users', '/dashboard/users', Record<never, never>, Record<never, never>>,
    'fplogin': RouteRecordInfo<'fplogin', '/FP-login', Record<never, never>, Record<never, never>>,
    'game-connect-wallet': RouteRecordInfo<'game-connect-wallet', '/game/connect-wallet', Record<never, never>, Record<never, never>>,
    'game-daily': RouteRecordInfo<'game-daily', '/game/daily', Record<never, never>, Record<never, never>>,
    'game-daily-index copy': RouteRecordInfo<'game-daily-index copy', '/game/daily/index copy', Record<never, never>, Record<never, never>>,
    'game-inventory': RouteRecordInfo<'game-inventory', '/game/inventory', Record<never, never>, Record<never, never>>,
    'game-jackpot': RouteRecordInfo<'game-jackpot', '/game/jackpot', Record<never, never>, Record<never, never>>,
    'game-menu': RouteRecordInfo<'game-menu', '/game/menu', Record<never, never>, Record<never, never>>,
    'game-pk': RouteRecordInfo<'game-pk', '/game/pk', Record<never, never>, Record<never, never>>,
    'game-referral': RouteRecordInfo<'game-referral', '/game/referral', Record<never, never>, Record<never, never>>,
    'game-treasure': RouteRecordInfo<'game-treasure', '/game/treasure', Record<never, never>, Record<never, never>>,
    'home': RouteRecordInfo<'home', '/home', Record<never, never>, Record<never, never>>,
    'telegram-auth': RouteRecordInfo<'telegram-auth', '/telegram-auth', Record<never, never>, Record<never, never>>,
    'telegram-login-token': RouteRecordInfo<'telegram-login-token', '/telegram-login/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    'telegram-login-admin-token': RouteRecordInfo<'telegram-login-admin-token', '/telegram-login-admin/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
  }
}
